### PR TITLE
Reimagining global 

### PR DESCRIPTION
**Pull request by johnx25bd**
RWOT9 paper submission

### CODE REVIEW

**Comment by ChristopherA** [comment]
There are merge conflicts.

**Comment by johnx25bd** [comment]
Hope that resolved them - thank you.

**Comment by jandrieu** [comment]
Could you try again? Add @jandrieu to your comment so I can process ASAP.

**Comment by johnx25bd** [comment]
@jandrieu How's this? I've got a green check - "no conflicts with the base branch".

**Pull request merged**
