### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by bumblefudge**
new summary/abstract, in addition to picking only one advanced topic to propose (sorry again!)

### CODE REVIEW

**Comment by jandrieu** [comment]
Please fix the merge conflicts.

**Comment by jandrieu** [comment]
@bumblefudge We're still waiting for fixes for the merge conflicts.

**Comment by bumblefudge** [comment]
Think I got it?  Just an artifact of asynchronous commits, I think.

**Comment by jandrieu** [comment]
@bumblefudge Did this merge? It looks like you just closed it without merging. =(

**Pull request merged**
