### PR TITLE
add topic paper for MITM attacks

### PR DESCRIPTION
**Pull request by kdenhartog**
Signed-off-by: kdenhartog <gpg@kyledenhartog.com>

### CODE REVIEW

**Comment by jandrieu** [comment]
Kyle, could you update to fix the merge conflicts?

**Comment by kdenhartog** [comment]
> Kyle, could you update to fix the merge conflicts?

Fixed it.

**Comment by jandrieu** [comment]
Shoot. Please try again. I'll send you the code separately while we deal with merge issues.

**Comment by kdenhartog** [comment]
> Shoot. Please try again. I'll send you the code separately while we deal with merge issues.

Take 2. I'll send you an email to follow up about the code.

**Pull request merged**
