### PR TITLE
Suggestions (including AMA authorship)

### PR DESCRIPTION
**Pull request by jandrieu**
Clean up the language introducing the first day (to be more active). Also added AMA link and author guidelines. Also, added "draft" to language about the Friday paper (it's not really *final*).

### CODE REVIEW

**Review by ChristopherA — COMMENTED** [review]
Did we say anywhere that we use CC licenses for documents and open source licenses for others?

**Comment by ChristopherA** [comment]
@shannona: You should look this over, merge it, add something about CC, and fix anything else you spot for consistent voice.

**Comment by shannona** [comment]
Thanks for the updates Joe. (And I'll get something about licenses tomorrow.)

**Comment by shannona** [comment]
Added the mention of the CC license under publishing; updated the title of the AMA authorship section for voice consistency. Thanks, folks!

**Pull request merged**
